// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_ueditor.proto

/* eslint-disable */
import { Observable } from "rxjs";
import {
  type UEditorRequest,
  type UEditorResponse,
  type UEditorUploadRequest,
  type UEditorUploadResponse,
} from "../../../file/service/v1/ueditor.pb";

/** UEditor后端服务 */
export interface UEditorService {
  /** UEditor API */
  UEditorAPI(request: UEditorRequest): Promise<UEditorResponse>;
  /** 上传文件 */
  UploadFile(request: Observable<UEditorUploadRequest>): Promise<UEditorUploadResponse>;
}
