// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: file/service/v1/file.proto

/* eslint-disable */

/** 前端上传文件所用的HTTP方法 */
export enum UploadMethod {
  Put = "Put",
  Post = "Post",
}

/** 获取对象存储上传链接 - 请求 */
export interface OssUploadUrlRequest {
  /** 上传文件所用的HTTP方法 */
  method: UploadMethod;
  /** 文件的MIME类型 */
  contentType?:
    | string
    | null
    | undefined;
  /** 文件桶名称，如果不填写，将会根据文件名或者MIME类型进行自动解析。 */
  bucketName?:
    | string
    | null
    | undefined;
  /** 远端的文件路径，可以不填写。 */
  filePath?:
    | string
    | null
    | undefined;
  /** 文件名，如果不填写，则会生成UUID，有同名文件也会改为UUID。 */
  fileName?: string | null | undefined;
}

/** 获取对象存储上传链接 - 回应 */
export interface OssUploadUrlResponse {
  /** 文件的上传链接，默认1个小时的过期时间。 */
  uploadUrl: string;
  /** 文件的下载链接 */
  downloadUrl: string;
  /** 文件桶名称 */
  bucketName?:
    | string
    | null
    | undefined;
  /** 文件名 */
  objectName: string;
  formData: Map<string, string>;
}

export interface OssUploadUrlResponse_FormDataEntry {
  key: string;
  value: string;
}

export interface GetDownloadUrlRequest {
}

export interface GetDownloadUrlResponse {
}

export interface ListFileRequest {
  /** 文件桶名称 */
  bucketName?:
    | string
    | null
    | undefined;
  /** 文件夹名称 */
  folder?:
    | string
    | null
    | undefined;
  /** 是否递归文件夹 */
  recursive?: boolean | null | undefined;
}

export interface ListFileResponse {
  files: string[];
}

export interface DeleteFileRequest {
  /** 文件桶名称 */
  bucketName?:
    | string
    | null
    | undefined;
  /** 文件名 */
  objectName?: string | null | undefined;
}

export interface DeleteFileResponse {
}

export interface UploadFileRequest {
  /** 文件桶名称 */
  bucketName?:
    | string
    | null
    | undefined;
  /** 文件名 */
  objectName?:
    | string
    | null
    | undefined;
  /** 文件内容 */
  file?: Uint8Array | null | undefined;
}

export interface UploadFileResponse {
  url: string;
}

/** 文件服务 */
export interface FileService {
  /** 获取对象存储（OSS）上传链接 */
  OssUploadUrl(request: OssUploadUrlRequest): Promise<OssUploadUrlResponse>;
  /** 获取对象存储（OSS）下载链接 */
  GetDownloadUrl(request: GetDownloadUrlRequest): Promise<GetDownloadUrlResponse>;
  /** 获取文件夹下面的文件列表 */
  ListFile(request: ListFileRequest): Promise<ListFileResponse>;
  /** 删除一个文件 */
  DeleteFile(request: DeleteFileRequest): Promise<DeleteFileResponse>;
  /** 上传文件 */
  UploadFile(request: UploadFileRequest): Promise<UploadFileResponse>;
}
