// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: file/service/v1/ueditor.proto

/* eslint-disable */

/** 动作 */
export enum UEditorAction {
  /** config - 配置 */
  config = "config",
  /** listFile - 文件 */
  listFile = "listFile",
  /** listImage - 图片 */
  listImage = "listImage",
  /** uploadFile - 文件 */
  uploadFile = "uploadFile",
  /** uploadImage - 图片 */
  uploadImage = "uploadImage",
  /** uploadVideo - 视频 */
  uploadVideo = "uploadVideo",
  /** uploadScrawl - 涂鸦图片 */
  uploadScrawl = "uploadScrawl",
  /** catchImage - 抓取远程图片 */
  catchImage = "catchImage",
}

export interface File {
  fileName: string;
  mime: string;
  content: Uint8Array;
}

export interface UEditorRequest {
  action: string;
  encode: string;
  start: number;
  size: number;
}

export interface UEditorResponse {
  /** 执行上传图片的action名称 */
  imageActionName?:
    | string
    | null
    | undefined;
  /** 提交的图片表单名称 */
  imageFieldName?:
    | string
    | null
    | undefined;
  /** 上传大小限制，单位B */
  imageMaxSize?:
    | string
    | null
    | undefined;
  /** 上传图片格式显示 */
  imageAllowFiles: string[];
  /** 是否压缩图片,默认是true */
  imageCompressEnable?:
    | boolean
    | null
    | undefined;
  /** 图片压缩最长边限制 */
  imageCompressBorder?:
    | string
    | null
    | undefined;
  /** 插入的图片浮动方式 */
  imageInsertAlign?:
    | string
    | null
    | undefined;
  /** 图片访问路径前缀 */
  imageUrlPrefix?:
    | string
    | null
    | undefined;
  /** 上传保存路径,可以自定义保存路径和文件名格式 */
  imagePathFormat?:
    | string
    | null
    | undefined;
  /** 执行上传涂鸦的action名称 */
  scrawlActionName?:
    | string
    | null
    | undefined;
  /** 提交的图片表单名称 */
  scrawlFieldName?:
    | string
    | null
    | undefined;
  /** 上传大小限制，单位B */
  scrawlMaxSize?:
    | string
    | null
    | undefined;
  /** 图片访问路径前缀 */
  scrawlUrlPrefix?:
    | string
    | null
    | undefined;
  /**  */
  scrawlInsertAlign?:
    | string
    | null
    | undefined;
  /** 上传保存路径,可以自定义保存路径和文件名格式 */
  scrawlPathFormat?:
    | string
    | null
    | undefined;
  /** 执行上传截图的action名称 */
  snapscreenActionName?:
    | string
    | null
    | undefined;
  /** 图片访问路径前缀 */
  snapscreenUrlPrefix?:
    | string
    | null
    | undefined;
  /** 插入的图片浮动方式 */
  snapscreenInsertAlign?:
    | string
    | null
    | undefined;
  /** 上传保存路径,可以自定义保存路径和文件名格式 */
  snapscreenPathFormat?:
    | string
    | null
    | undefined;
  /** 执行抓取远程图片的action名称 */
  catcherActionName?:
    | string
    | null
    | undefined;
  /** 提交的图片列表表单名称 */
  catcherFieldName?:
    | string
    | null
    | undefined;
  /**  */
  catcherLocalDomain: string[];
  /** 图片访问路径前缀 */
  catcherUrlPrefix?:
    | string
    | null
    | undefined;
  /** 上传大小限制，单位B */
  catcherMaxSize?:
    | string
    | null
    | undefined;
  /** 列出的文件类型 */
  catcherAllowFiles: string[];
  /** 上传保存路径,可以自定义保存路径和文件名格式 */
  catcherPathFormat?:
    | string
    | null
    | undefined;
  /** 执行上传视频的action名称 */
  videoActionName?:
    | string
    | null
    | undefined;
  /** 提交的视频表单名称 */
  videoFieldName?:
    | string
    | null
    | undefined;
  /** 视频访问路径前缀 */
  videoUrlPrefix?:
    | string
    | null
    | undefined;
  /** 上传大小限制，单位B，默认100MB */
  videoMaxSize?:
    | string
    | null
    | undefined;
  /** 列出的文件类型 */
  videoAllowFiles: string[];
  /** 上传保存路径,可以自定义保存路径和文件名格式 */
  videoPathFormat?:
    | string
    | null
    | undefined;
  /** 执行上传视频的action名称 */
  fileActionName?:
    | string
    | null
    | undefined;
  /** 提交的文件表单名称 */
  fileFieldName?:
    | string
    | null
    | undefined;
  /** 文件访问路径前缀 */
  fileUrlPrefix?:
    | string
    | null
    | undefined;
  /** 上传大小限制，单位B，默认50MB */
  fileMaxSize?:
    | string
    | null
    | undefined;
  /** 列出的文件类型 */
  fileAllowFiles: string[];
  /** 上传保存路径,可以自定义保存路径和文件名格式 */
  filePathFormat?:
    | string
    | null
    | undefined;
  /** 图片列表配置 */
  imageManagerActionName?:
    | string
    | null
    | undefined;
  /** 每次列出文件数量 */
  imageManagerListSize?:
    | string
    | null
    | undefined;
  /** 图片访问路径前缀 */
  imageManagerUrlPrefix?:
    | string
    | null
    | undefined;
  /** 插入的图片浮动方式，默认值：none */
  imageManagerInsertAlign?:
    | string
    | null
    | undefined;
  /** 列出的文件类型 */
  imageManagerAllowFiles: string[];
  /** 指定要列出图片的目录 */
  imageManagerListPath?:
    | string
    | null
    | undefined;
  /** 文件列表配置 */
  fileManagerActionName?:
    | string
    | null
    | undefined;
  /** 指定要列出文件的目录 */
  fileManagerUrlPrefix?:
    | string
    | null
    | undefined;
  /** 每次列出文件数量 */
  fileManagerListSize?:
    | string
    | null
    | undefined;
  /** 列出的文件类型 */
  fileManagerAllowFiles: string[];
  /** 列出的文件类型 */
  FileManagerListPath?:
    | string
    | null
    | undefined;
  /** 公式配置 */
  formulaConfig?:
    | UEditorResponse_FormulaConfig
    | null
    | undefined;
  /** 上传状态，上传成功时必须返回"SUCCESS" */
  state?: string | null | undefined;
  start?: number | null | undefined;
  total?: number | null | undefined;
  list: UEditorResponse_Item[];
}

export interface UEditorResponse_FormulaConfig {
  /** 公式渲染的路径 */
  imageUrlTemplate: string;
}

export interface UEditorResponse_Item {
  url: string;
  mtime: string;
}

export interface UEditorUploadRequest {
  action: string;
  file?: File | null | undefined;
}

export interface UEditorUploadResponse {
  /** 上传状态，上传成功时必须返回"SUCCESS" */
  state?:
    | string
    | null
    | undefined;
  /** 返回的地址 */
  url?:
    | string
    | null
    | undefined;
  /** 新文件名 */
  title?:
    | string
    | null
    | undefined;
  /** 原始文件名 */
  original?:
    | string
    | null
    | undefined;
  /** 文件类型 */
  type?:
    | string
    | null
    | undefined;
  /** 文件大小 */
  size?: number | null | undefined;
  list: UEditorUploadResponse_Item[];
}

export interface UEditorUploadResponse_Item {
  /** 上传状态，上传成功时必须返回"SUCCESS" */
  state: string;
  /** 返回的地址 */
  url?:
    | string
    | null
    | undefined;
  /** 新文件名 */
  title?:
    | string
    | null
    | undefined;
  /** 原始文件名 */
  original?:
    | string
    | null
    | undefined;
  /** 文件类型 */
  type?:
    | string
    | null
    | undefined;
  /** 文件大小 */
  size?: number | null | undefined;
}

export interface UEditorListResponse {
  state: string;
  start: number;
  total: number;
  list: UEditorListResponse_Item[];
}

export interface UEditorListResponse_Item {
  url: string;
  mtime: string;
}

/** UEditor后端服务 */
export interface UEditorService {
  /** UEditor API */
  UEditorAPI(request: UEditorRequest): Promise<UEditorResponse>;
  /** 上传文件 */
  UploadFile(request: UEditorUploadRequest): Promise<UEditorUploadResponse>;
}
